# Generated by Django 3.2a1 on 2023-08-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0002_alter_reservation_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departureCity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='middleName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
